### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by dineshbhosale**
Fixed typo

### CODE REVIEW

**Comment by dineshbhosale** [comment]
I signed it!

**Comment by dineshbhosale** [comment]
I signed it!

**Comment by dineshbhosale** [comment]
I signed it!

**Comment by nshahan** [comment]
Thanks for catching the typo. I'll get this fixed in the next sync from our internal repo.

**Comment by nshahan** [comment]
The readme was updated in the latest sync from our internal repo #216 and I made sure this fix was in it. Thanks!

**Pull request closed without merging**
